[project]
name = "kiwi"
version = "1.0.5"
requires-python = ">=3.12"
dependencies = [
    "flask>=2.0.0",
    "flask-oidc>=2.0.0",
    "authlib>=1.0.0",
    "Flask-Session>=0.5.0",
    "requests>=2.28.0",
    "gunicorn>=20.1.0",
]
