repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: certmanager-crds
  namespace: cert-manager
  chart: ./crds-chart
  version: v1.1.0
  installed: true
  hooks:
  - events: [prepare]
    showlogs: true
    command: wget
    args:
      - -O
      - ./crds-chart/templates/00-crds.yaml
      - https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.crds.yaml

- name: certmanager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.19.2
  installed: true
  needs:
    - cert-manager/certmanager-crds
  values:
    - values.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args: ["label", "--overwrite", "namespace", "cert-manager", "cert-manager.io/disable-validation=true"]
  # Wait for some apiservices to be ready, see https://github.com/helm/helm/issues/6361
  - events: ["postsync"]
    showlogs: true
    command: "sleep"
    args: ["120"]

- name: certmanager-issuer
  namespace: cert-manager
  chart: ./issuer-chart
  version: v1.19.2
  installed: true
  disableValidation: true
  needs:
    - cert-manager/certmanager
  values:
    - letsEncryptClusterIssuer:
        #
        # IMPORTANT: This value MUST be set to a valid email.
        #
        email: ict.services@bindinc.nl
