apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-config
data:
  APP_IMAGE_BLUE: registry.kiwi.svc.cluster.local/kiwi/portal:local
  APP_IMAGE_GREEN: registry.kiwi.svc.cluster.local/kiwi/portal:local
  ACTIVE_TRACK: blue
  PREVIEW_TRACK: green
