apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kiwi

resources:
  - ../../base

images:
  - name: kiwi/portal
    newName: registry.kiwi.svc.cluster.local/kiwi/portal
    newTag: local

patches:
  - path: service-nodeport.yaml
