apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-blue
  labels:
    app.kubernetes.io/name: kiwi
    app.kubernetes.io/part-of: kiwi
    track: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kiwi
      track: blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kiwi
        app.kubernetes.io/part-of: kiwi
        track: blue
    spec:
      containers:
        - name: portal
          image: kiwi/portal:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
