apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi
  labels:
    app.kubernetes.io/name: kiwi
    app.kubernetes.io/part-of: kiwi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kiwi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kiwi
        app.kubernetes.io/part-of: kiwi
    spec:
      containers:
        - name: portal
          image: kiwi/portal:latest
          ports:
            - name: http
              containerPort: 8000
