apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - service-preview.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: deploy-config
    envs:
      - deploy.env

replacements:
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.NAMESPACE
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: kiwi-blue
        fieldPaths:
          - metadata.namespace
        options:
          create: true
      - select:
          kind: Service
          name: kiwi
        fieldPaths:
          - metadata.namespace
        options:
          create: true
      - select:
          kind: Deployment
          name: kiwi-green
        fieldPaths:
          - metadata.namespace
        options:
          create: true
      - select:
          kind: Service
          name: kiwi-preview
        fieldPaths:
          - metadata.namespace
        options:
          create: true
      - select:
          kind: ConfigMap
          name: deploy-config
        fieldPaths:
          - metadata.namespace
        options:
          create: true
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.APP_PORT
    targets:
      - select:
          kind: Deployment
          name: kiwi-blue
        fieldPaths:
          - spec.template.spec.containers.0.ports.0.containerPort
      - select:
          kind: Deployment
          name: kiwi-green
        fieldPaths:
          - spec.template.spec.containers.0.ports.0.containerPort
      - select:
          kind: Service
          name: kiwi
        fieldPaths:
          - spec.ports.0.targetPort
      - select:
          kind: Service
          name: kiwi-preview
        fieldPaths:
          - spec.ports.0.targetPort
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.SERVICE_PORT
    targets:
      - select:
          kind: Service
          name: kiwi
        fieldPaths:
          - spec.ports.0.port
      - select:
          kind: Service
          name: kiwi-preview
        fieldPaths:
          - spec.ports.0.port
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.ACTIVE_TRACK
    targets:
      - select:
          kind: Service
          name: kiwi
        fieldPaths:
          - spec.selector.track
        options:
          create: true
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.PREVIEW_TRACK
    targets:
      - select:
          kind: Service
          name: kiwi-preview
        fieldPaths:
          - spec.selector.track
        options:
          create: true
