apiVersion: v1
kind: Service
metadata:
  name: kiwi-preview
  labels:
    app.kubernetes.io/name: kiwi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kiwi
    track: green
  ports:
    - name: http
      port: 80
      targetPort: 8000
