apiVersion: v1
kind: Service
metadata:
  name: kiwi-portal
  labels:
    app.kubernetes.io/name: kiwi-portal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kiwi-portal
  ports:
    - name: http
      port: 80
      targetPort: 8000
