name: cert-manager-crds
version: v1.1.0
appVersion: 1.19.2
description: "Local chart to install cert-manager CRDs"
sources:
  - "https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.crds.yaml"
