apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment-prod-blue.yaml
    target:
      kind: Deployment
      name: kiwi-blue
  - path: deployment-prod-green.yaml
    target:
      kind: Deployment
      name: kiwi-green
  - path: deploy-config.yaml
    target:
      kind: ConfigMap
      name: deploy-config

replacements:
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.APP_IMAGE_BLUE
    targets:
      - select:
          kind: Deployment
          name: kiwi-blue
        fieldPaths:
          - spec.template.spec.containers.0.image
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.APP_IMAGE_GREEN
    targets:
      - select:
          kind: Deployment
          name: kiwi-green
        fieldPaths:
          - spec.template.spec.containers.0.image
