apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment-prod.yaml

replacements:
  - source:
      kind: ConfigMap
      name: deploy-config
      fieldPath: data.APP_IMAGE_PROD
    targets:
      - select:
          kind: Deployment
          name: kiwi-portal
        fieldPaths:
          - spec.template.spec.containers.0.image
